// src/plugins/theme.js
const staticPrimaryColor = '#772083' // default kalau localStorage kosong
const staticColors = {} // kalau ada warna statik tambahan

export const theme = {
  defaultTheme: 'light',
  themes: {
    light: {
      dark: false,
      colors: {
        'primary': localStorage.getItem('app-lightThemePrimaryColor') || staticPrimaryColor,
        'primary-subtle': '#FFF1E7',
        'on-primary': '#85bdfd',
        'secondary': '#8592A3',
        'on-secondary': '#fff',
        'success': '#499c1c',
        'success-darker': '#70cc3f',
        'success-subtle': '#d3f7c0',
        'on-success': '#fff',
        'info': '#03C3EC',
        'on-info': '#fff',
        'warning': '#FFAB00',
        'on-warning': '#fff',
        'error': '#ff1d1d',
        'background': '#F5F5F9',
        'on-background': '#32475C',
        'on-surface': '#32475C',
        'second-layer': '#F5F5F9',
        'grey-50': '#FAFAFA',
        'grey-100': '#EBEEF0',
        'grey-200': '#EEEEEE',
        'grey-300': '#E0E0E0',
        'grey-400': '#BDBDBD',
        'grey-500': '#9E9E9E',
        'grey-600': '#757575',
        'grey-700': '#616161',
        'grey-800': '#424242',
        'grey-900': '#212121',
        'expanded-row-background': '#FAFAFA',
        'perfect-scrollbar-thumb': '#DBDADE',
        'skin-bordered-background': '#fff',
        'skin-bordered-surface': '#fff',
        'blue-light': '#D6EEFE',
        'blue-dark': '#0077B5',
        'purple-light': '#8c48fa',
        'purple-dark': '#23193e',
        'green-light': '#E6F4EA',
        'green-dark': '#00966D',
        'yellow-light': '#FFF2D7',
        'yellow-dark': '#FFB800',
        'teal-light': '#B2FFFC',
        'teal-dark': '#0097A7',
        'brown-light': '#E6DFDE',
        'brown-dark': '#795548',
        'lavender-light': '#E6DFDE',
        'lavender-dark': '#6c5ce7',
        'orange-light': '#FEE4DA',
        'orange-dark': '#ffa777',
        'pink-light': '#ffdbf8',
        'pink-dark': '#C02D8E',
        'battery-status-unknown': '#FFCC22',
        ...staticColors,
      },
      variables: {
        'code-color': '#d400ff',
        'overlay-scrim-background': '#32475C',
        'overlay-scrim-opacity': 0.5,
        'border-color': '#32475C',
        'snackbar-background': '#32475C',
        'snackbar-color': '#ffffff',
        'tooltip-background': '#262732',
        'tooltip-opacity': 0.9,
        'shadow-key-umbra-opacity': 'rgba(var(--v-theme-on-surface), 0.06)',
        'shadow-key-penumbra-opacity': 'rgba(var(--v-theme-on-surface), 0.04)',
        'shadow-key-ambient-opacity': 'rgba(var(--v-theme-on-surface), 0.02)',
      },
    },
    dark: {
      dark: true,
      colors: {
        'primary': localStorage.getItem('app-darkThemePrimaryColor') || staticPrimaryColor,
        'primary-subtle': '#2b2c40',
        'on-primary': '#fff',
        'secondary': '#8592A3',
        'secondary-subtle': '#2b2c40',
        'on-secondary': '#fff',
        'success': '#499c1c',
        'success-darker': '#70cc3f',
        'success-subtle': '#d3f7c0',
        'on-success': '#fff',
        'info': '#03C3EC',
        'on-info': '#fff',
        'warning': '#FFAB00',
        'on-warning': '#fff',
        'error': '#FF3E1D',
        'background': '#000000',
        'on-background': '#DBDBEB',
        'surface': '#2E2E2E',
        'on-surface': '#DBDBEB',
        'second-layer': '#454545',
        'grey-50': '#2A2E42',
        'grey-100': '#444463',
        'grey-200': '#4A5072',
        'grey-300': '#5E6692',
        'grey-400': '#7983BB',
        'grey-500': '#8692D0',
        'grey-600': '#AAB3DE',
        'grey-700': '#B6BEE3',
        'grey-800': '#CFD3EC',
        'grey-900': '#E7E9F6',
        'expanded-row-background': '#121212',
        'perfect-scrollbar-thumb': '#4A5072',
        'skin-bordered-background': '#2b2c40',
        'skin-bordered-surface': '#2b2c40',
        'blue-light': '#D6EEFE',
        'blue-dark': '#0077B5',
        'purple-light': '#E9E2F4',
        'purple-dark': '#6651A5',
        'green-light': '#E6F4EA',
        'green-dark': '#00966D',
        'yellow-light': '#FFF2D7',
        'yellow-dark': '#FFB800',
        'teal-light': '#B2FFFC',
        'teal-dark': '#0097A7',
        'brown-light': '#E6DFDE',
        'brown-dark': '#795548',
        'lavender-light': '#E6DFDE',
        'lavender-dark': '#6c5ce7',
        'orange-light': '#FEE4DA',
        'orange-dark': '#ffa777',
        'pink-light': '#ffdbf8',
        'pink-dark': '#C02D8E',
        'battery-status-unknown': '#FFCC22',
        ...staticColors,
      },
      variables: {
        'code-color': '#d400ff',
        'overlay-scrim-background': '#0D0E24',
        'overlay-scrim-opacity': 0.6,
        'border-color': '#DBDBEB',
        'snackbar-background': '#DBDBEB',
        'snackbar-color': '#2B2C40',
        'tooltip-background': '#464A65',
        'tooltip-opacity': 0.9,
        'shadow-key-umbra-opacity': 'rgba(20, 21, 33, 0.06)',
        'shadow-key-penumbra-opacity': 'rgba(20, 21, 33, 0.04)',
        'shadow-key-ambient-opacity': 'rgba(20, 21, 33, 0.02)',
      },
    },
  },
}
